import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Unicode 이모지 및 특수문자 대량 데이터
const emojiData = {
  smileys: [
    { char: "😀", name_ko: "웃는 얼굴", name_en: "grinning face", tags: ["웃음", "행복", "기쁨", "미소", "grinning", "happy", "smile"] },
    { char: "😃", name_ko: "크게 웃는 얼굴", name_en: "grinning face with big eyes", tags: ["웃음", "행복", "기쁨", "미소", "grinning", "happy", "smile"] },
    { char: "😄", name_ko: "눈을 감고 웃는 얼굴", name_en: "grinning face with smiling eyes", tags: ["웃음", "행복", "기쁨", "미소", "grinning", "happy", "smile"] },
    { char: "😁", name_ko: "넓게 웃는 얼굴", name_en: "beaming face with smiling eyes", tags: ["웃음", "행복", "기쁨", "미소", "grinning", "happy", "smile"] },
    { char: "😆", name_ko: "크게 웃으며 눈을 감은 얼굴", name_en: "grinning squinting face", tags: ["웃음", "행복", "기쁨", "미소", "grinning", "happy", "smile"] },
    { char: "😅", name_ko: "땀을 흘리며 웃는 얼굴", name_en: "grinning face with sweat", tags: ["웃음", "땀", "안심", "sweat", "relief"] },
    { char: "🤣", name_ko: "바닥에 구르며 웃는 얼굴", name_en: "rolling on the floor laughing", tags: ["웃음", "폭소", "재미", "laughing", "funny"] },
    { char: "😂", name_ko: "눈물을 흘리며 웃는 얼굴", name_en: "face with tears of joy", tags: ["웃음", "눈물", "폭소", "tears", "joy", "laughing"] },
    { char: "🙂", name_ko: "살짝 웃는 얼굴", name_en: "slightly smiling face", tags: ["미소", "친절", "긍정", "smile", "kind", "positive"] },
    { char: "🙃", name_ko: "거꾸로 된 얼굴", name_en: "upside-down face", tags: ["장난", "재미", "유머", "playful", "funny", "humor"] },
    { char: "😉", name_ko: "윙크하는 얼굴", name_en: "winking face", tags: ["윙크", "장난", "친근", "wink", "playful", "friendly"] },
    { char: "😊", name_ko: "미소 짓는 얼굴", name_en: "smiling face with smiling eyes", tags: ["미소", "행복", "기쁨", "smile", "happy", "joy"] },
    { char: "😇", name_ko: "후광이 있는 얼굴", name_en: "smiling face with halo", tags: ["천사", "순수", "선량", "angel", "innocent", "good"] },
    { char: "🥰", name_ko: "하트가 있는 미소 얼굴", name_en: "smiling face with hearts", tags: ["사랑", "미소", "행복", "love", "smile", "happy"] },
    { char: "😍", name_ko: "하트 눈 얼굴", name_en: "smiling face with heart-eyes", tags: ["사랑", "매력", "좋아함", "love", "attractive", "like"] },
    { char: "🤩", name_ko: "별 눈 얼굴", name_en: "star-struck", tags: ["별", "놀람", "감동", "star", "surprise", "amazed"] },
    { char: "😘", name_ko: "키스하는 얼굴", name_en: "face blowing a kiss", tags: ["키스", "사랑", "애정", "kiss", "love", "affection"] },
    { char: "😗", name_ko: "키스하는 얼굴", name_en: "kissing face", tags: ["키스", "사랑", "애정", "kiss", "love", "affection"] },
    { char: "😚", name_ko: "눈을 감고 키스하는 얼굴", name_en: "kissing face with closed eyes", tags: ["키스", "사랑", "애정", "kiss", "love", "affection"] },
    { char: "😙", name_ko: "미소 짓고 키스하는 얼굴", name_en: "kissing face with smiling eyes", tags: ["키스", "사랑", "애정", "kiss", "love", "affection"] },
    { char: "😋", name_ko: "맛있게 먹는 얼굴", name_en: "face savoring food", tags: ["맛", "음식", "먹기", "taste", "food", "eating"] },
    { char: "😛", name_ko: "혀를 내민 얼굴", name_en: "face with tongue", tags: ["혀", "장난", "재미", "tongue", "playful", "funny"] },
    { char: "😜", name_ko: "윙크하며 혀를 내민 얼굴", name_en: "winking face with tongue", tags: ["혀", "윙크", "장난", "tongue", "wink", "playful"] },
    { char: "🤪", name_ko: "미친 얼굴", name_en: "zany face", tags: ["미친", "장난", "재미", "crazy", "playful", "funny"] },
    { char: "😝", name_ko: "눈을 감고 혀를 내민 얼굴", name_en: "squinting face with tongue", tags: ["혀", "장난", "재미", "tongue", "playful", "funny"] },
    { char: "🤑", name_ko: "돈 입 얼굴", name_en: "money-mouth face", tags: ["돈", "부자", "욕심", "money", "rich", "greedy"] },
    { char: "🤗", name_ko: "포옹하는 얼굴", name_en: "hugging face", tags: ["포옹", "사랑", "친근", "hug", "love", "friendly"] },
    { char: "🤭", name_ko: "입을 가린 얼굴", name_en: "face with hand over mouth", tags: ["비밀", "놀람", "조용", "secret", "surprise", "quiet"] },
    { char: "🤫", name_ko: "조용히 하는 얼굴", name_en: "shushing face", tags: ["조용", "비밀", "침묵", "quiet", "secret", "silence"] },
    { char: "🤔", name_ko: "생각하는 얼굴", name_en: "thinking face", tags: ["생각", "고민", "의문", "thinking", "wondering", "question"] },
    { char: "🤐", name_ko: "지퍼 입 얼굴", name_en: "zipper-mouth face", tags: ["침묵", "비밀", "조용", "silence", "secret", "quiet"] },
    { char: "🤨", name_ko: "한쪽 눈썹 올린 얼굴", name_en: "face with raised eyebrow", tags: ["의심", "의문", "호기심", "suspicious", "question", "curious"] },
    { char: "😐", name_ko: "무표정 얼굴", name_en: "neutral face", tags: ["무표정", "중립", "평범", "neutral", "expressionless", "normal"] },
    { char: "😑", name_ko: "무표정 얼굴", name_en: "expressionless face", tags: ["무표정", "중립", "평범", "neutral", "expressionless", "normal"] },
    { char: "😶", name_ko: "입 없는 얼굴", name_en: "face without mouth", tags: ["무표정", "침묵", "말없음", "expressionless", "silence", "speechless"] },
    { char: "😏", name_ko: "비웃는 얼굴", name_en: "smirking face", tags: ["비웃음", "장난", "교활", "smirk", "playful", "sly"] },
    { char: "😒", name_ko: "불만스러운 얼굴", name_en: "unamused face", tags: ["불만", "지루", "무관심", "unamused", "bored", "indifferent"] },
    { char: "🙄", name_ko: "눈을 굴리는 얼굴", name_en: "face with rolling eyes", tags: ["눈굴림", "지루", "무관심", "rolling eyes", "bored", "indifferent"] },
    { char: "😬", name_ko: "긴장한 얼굴", name_en: "grimacing face", tags: ["긴장", "불편", "어색", "nervous", "uncomfortable", "awkward"] },
    { char: "🤥", name_ko: "거짓말하는 얼굴", name_en: "lying face", tags: ["거짓말", "거짓", "의심", "lying", "false", "suspicious"] },
    { char: "😌", name_ko: "안심하는 얼굴", name_en: "relieved face", tags: ["안심", "편안", "만족", "relieved", "comfortable", "satisfied"] },
    { char: "😔", name_ko: "우울한 얼굴", name_en: "pensive face", tags: ["우울", "슬픔", "생각", "sad", "depressed", "thinking"] },
    { char: "😪", name_ko: "졸린 얼굴", name_en: "sleepy face", tags: ["졸림", "피곤", "수면", "sleepy", "tired", "sleep"] },
    { char: "🤤", name_ko: "침 흘리는 얼굴", name_en: "drooling face", tags: ["침", "배고픔", "욕심", "drool", "hungry", "desire"] },
    { char: "😴", name_ko: "자는 얼굴", name_en: "sleeping face", tags: ["수면", "졸림", "피곤", "sleep", "sleepy", "tired"] },
    { char: "😷", name_ko: "마스크 쓴 얼굴", name_en: "face with medical mask", tags: ["마스크", "병", "보호", "mask", "sick", "protection"] },
    { char: "🤒", name_ko: "열이 있는 얼굴", name_en: "face with thermometer", tags: ["열", "병", "아픔", "fever", "sick", "pain"] },
    { char: "🤕", name_ko: "붕대 감은 얼굴", name_en: "face with head-bandage", tags: ["부상", "아픔", "치료", "injury", "pain", "treatment"] },
    { char: "🤢", name_ko: "구역질 나는 얼굴", name_en: "nauseated face", tags: ["구역질", "병", "불편", "nauseated", "sick", "uncomfortable"] },
    { char: "🤮", name_ko: "토하는 얼굴", name_en: "face vomiting", tags: ["토함", "병", "불편", "vomiting", "sick", "uncomfortable"] },
    { char: "🤧", name_ko: "재채기하는 얼굴", name_en: "sneezing face", tags: ["재채기", "병", "감기", "sneezing", "sick", "cold"] },
    { char: "🥵", name_ko: "뜨거운 얼굴", name_en: "hot face", tags: ["뜨거움", "열", "더위", "hot", "heat", "warm"] },
    { char: "🥶", name_ko: "차가운 얼굴", name_en: "cold face", tags: ["차가움", "추위", "춥다", "cold", "freezing", "chilly"] },
    { char: "😵", name_ko: "어지러운 얼굴", name_en: "dizzy face", tags: ["어지러움", "현기증", "병", "dizzy", "vertigo", "sick"] },
    { char: "🤯", name_ko: "폭발하는 머리", name_en: "exploding head", tags: ["폭발", "놀람", "충격", "exploding", "surprise", "shock"] },
    { char: "🤠", name_ko: "카우보이 모자 얼굴", name_en: "cowboy hat face", tags: ["카우보이", "모자", "서부", "cowboy", "hat", "western"] },
    { char: "🥳", name_ko: "파티하는 얼굴", name_en: "partying face", tags: ["파티", "축하", "기쁨", "party", "celebration", "joy"] },
    { char: "🥸", name_ko: "변장한 얼굴", name_en: "disguised face", tags: ["변장", "가면", "숨김", "disguised", "mask", "hidden"] },
    { char: "😎", name_ko: "선글라스 쓴 웃는 얼굴", name_en: "smiling face with sunglasses", tags: ["선글라스", "멋", "시원", "sunglasses", "cool", "fresh"] },
    { char: "🤓", name_ko: "안경 쓴 얼굴", name_en: "nerd face", tags: ["안경", "공부", "지식", "glasses", "study", "knowledge"] },
    { char: "🧐", name_ko: "단안경 쓴 얼굴", name_en: "face with monocle", tags: ["단안경", "관찰", "호기심", "monocle", "observation", "curious"] },
    { char: "😕", name_ko: "혼란스러운 얼굴", name_en: "confused face", tags: ["혼란", "의문", "불확실", "confused", "question", "uncertain"] },
    { char: "😟", name_ko: "걱정스러운 얼굴", name_en: "worried face", tags: ["걱정", "불안", "근심", "worried", "anxious", "concern"] },
    { char: "🙁", name_ko: "약간 찡그린 얼굴", name_en: "slightly frowning face", tags: ["불만", "슬픔", "실망", "unhappy", "sad", "disappointed"] },
    { char: "☹️", name_ko: "찡그린 얼굴", name_en: "frowning face", tags: ["불만", "슬픔", "실망", "unhappy", "sad", "disappointed"] },
    { char: "😮", name_ko: "입 벌린 얼굴", name_en: "face with open mouth", tags: ["놀람", "입벌림", "의외", "surprise", "open mouth", "unexpected"] },
    { char: "😯", name_ko: "조용히 놀란 얼굴", name_en: "hushed face", tags: ["놀람", "조용", "충격", "surprise", "quiet", "shock"] },
    { char: "😲", name_ko: "놀란 얼굴", name_en: "astonished face", tags: ["놀람", "충격", "의외", "surprise", "shock", "unexpected"] },
    { char: "😳", name_ko: "얼굴 빨개진 얼굴", name_en: "flushed face", tags: ["부끄러움", "당황", "빨개짐", "embarrassed", "flushed", "blush"] },
    { char: "🥺", name_ko: "간청하는 얼굴", name_en: "pleading face", tags: ["간청", "부탁", "애원", "pleading", "request", "begging"] },
    { char: "😦", name_ko: "입 벌리고 찡그린 얼굴", name_en: "frowning face with open mouth", tags: ["불만", "놀람", "실망", "unhappy", "surprise", "disappointed"] },
    { char: "😧", name_ko: "고통스러운 얼굴", name_en: "anguished face", tags: ["고통", "아픔", "불편", "pain", "suffering", "uncomfortable"] },
    { char: "😨", name_ko: "두려워하는 얼굴", name_en: "fearful face", tags: ["두려움", "공포", "무서움", "fear", "scared", "afraid"] },
    { char: "😰", name_ko: "땀 흘리며 걱정하는 얼굴", name_en: "anxious face with sweat", tags: ["걱정", "땀", "불안", "worried", "sweat", "anxious"] },
    { char: "😥", name_ko: "실망하지만 안도하는 얼굴", name_en: "sad but relieved face", tags: ["실망", "안도", "복잡", "disappointed", "relieved", "complex"] },
    { char: "😢", name_ko: "우는 얼굴", name_en: "crying face", tags: ["울음", "슬픔", "눈물", "crying", "sad", "tears"] },
    { char: "😭", name_ko: "크게 우는 얼굴", name_en: "loudly crying face", tags: ["울음", "슬픔", "눈물", "crying", "sad", "tears"] },
    { char: "😱", name_ko: "비명 지르는 얼굴", name_en: "face screaming in fear", tags: ["비명", "공포", "놀람", "scream", "fear", "surprise"] },
    { char: "😖", name_ko: "고민하는 얼굴", name_en: "confounded face", tags: ["고민", "혼란", "불만", "confused", "troubled", "unhappy"] },
    { char: "😣", name_ko: "인내하는 얼굴", name_en: "persevering face", tags: ["인내", "고통", "참음", "persevering", "pain", "endurance"] },
    { char: "😞", name_ko: "실망한 얼굴", name_en: "disappointed face", tags: ["실망", "슬픔", "불만", "disappointed", "sad", "unhappy"] },
    { char: "😓", name_ko: "땀 흘리는 얼굴", name_en: "downcast face with sweat", tags: ["땀", "피곤", "불편", "sweat", "tired", "uncomfortable"] },
    { char: "😩", name_ko: "피곤한 얼굴", name_en: "weary face", tags: ["피곤", "지침", "불만", "tired", "exhausted", "unhappy"] },
    { char: "😫", name_ko: "지친 얼굴", name_en: "tired face", tags: ["피곤", "지침", "불만", "tired", "exhausted", "unhappy"] },
    { char: "🥱", name_ko: "하품하는 얼굴", name_en: "yawning face", tags: ["하품", "졸림", "피곤", "yawn", "sleepy", "tired"] },
    { char: "😤", name_ko: "콧김 나오는 얼굴", name_en: "face with steam from nose", tags: ["화남", "불만", "짜증", "angry", "unhappy", "annoyed"] },
    { char: "😡", name_ko: "화난 얼굴", name_en: "pouting face", tags: ["화남", "불만", "짜증", "angry", "unhappy", "annoyed"] },
    { char: "😠", name_ko: "화난 얼굴", name_en: "angry face", tags: ["화남", "불만", "짜증", "angry", "unhappy", "annoyed"] },
    { char: "🤬", name_ko: "욕하는 얼굴", name_en: "face with symbols on mouth", tags: ["욕", "화남", "불만", "swearing", "angry", "unhappy"] },
    { char: "😈", name_ko: "웃는 악마 얼굴", name_en: "smiling face with horns", tags: ["악마", "장난", "교활", "devil", "playful", "sly"] },
    { char: "👿", name_ko: "화난 악마 얼굴", name_en: "angry face with horns", tags: ["악마", "화남", "불만", "devil", "angry", "unhappy"] },
    { char: "💀", name_ko: "해골", name_en: "skull", tags: ["해골", "죽음", "무서움", "skull", "death", "scary"] },
    { char: "☠️", name_ko: "해골과 뼈", name_en: "skull and crossbones", tags: ["해골", "죽음", "위험", "skull", "death", "danger"] },
    { char: "💩", name_ko: "똥 얼굴", name_en: "pile of poo", tags: ["똥", "장난", "재미", "poo", "playful", "funny"] },
    { char: "🤡", name_ko: "광대 얼굴", name_en: "clown face", tags: ["광대", "장난", "재미", "clown", "playful", "funny"] },
    { char: "👹", name_ko: "오니", name_en: "ogre", tags: ["오니", "악마", "무서움", "ogre", "devil", "scary"] },
    { char: "👺", name_ko: "도깨비", name_en: "goblin", tags: ["도깨비", "악마", "무서움", "goblin", "devil", "scary"] },
    { char: "👻", name_ko: "유령", name_en: "ghost", tags: ["유령", "무서움", "할로윈", "ghost", "scary", "halloween"] },
    { char: "👽", name_ko: "외계인", name_en: "alien", tags: ["외계인", "우주", "신비", "alien", "space", "mystery"] },
    { char: "👾", name_ko: "외계 괴물", name_en: "alien monster", tags: ["외계인", "게임", "재미", "alien", "game", "funny"] },
    { char: "🤖", name_ko: "로봇", name_en: "robot", tags: ["로봇", "기계", "과학", "robot", "machine", "science"] },
    { char: "😺", name_ko: "웃는 고양이 얼굴", name_en: "grinning cat", tags: ["고양이", "웃음", "행복", "cat", "grinning", "happy"] },
    { char: "😸", name_ko: "크게 웃는 고양이 얼굴", name_en: "grinning cat with smiling eyes", tags: ["고양이", "웃음", "행복", "cat", "grinning", "happy"] },
    { char: "😹", name_ko: "눈물 흘리며 웃는 고양이", name_en: "cat with tears of joy", tags: ["고양이", "웃음", "눈물", "cat", "laughing", "tears"] },
    { char: "😻", name_ko: "하트 눈 고양이", name_en: "smiling cat with heart-eyes", tags: ["고양이", "사랑", "좋아함", "cat", "love", "like"] },
    { char: "😼", name_ko: "비웃는 고양이", name_en: "cat with wry smile", tags: ["고양이", "비웃음", "교활", "cat", "smirk", "sly"] },
    { char: "😽", name_ko: "키스하는 고양이", name_en: "kissing cat", tags: ["고양이", "키스", "사랑", "cat", "kiss", "love"] },
    { char: "🙀", name_ko: "놀란 고양이", name_en: "weary cat", tags: ["고양이", "놀람", "피곤", "cat", "surprise", "tired"] },
    { char: "😿", name_ko: "우는 고양이", name_en: "crying cat face", tags: ["고양이", "울음", "슬픔", "cat", "crying", "sad"] },
    { char: "😾", name_ko: "화난 고양이", name_en: "pouting cat", tags: ["고양이", "화남", "불만", "cat", "angry", "unhappy"] },
    { char: "👋", name_ko: "손 흔들기", name_en: "waving hand", tags: ["손", "인사", "안녕", "hand", "wave", "hello"] },
    { char: "🤚", name_ko: "손등", name_en: "raised back of hand", tags: ["손", "손등", "stop", "hand", "back", "stop"] },
    { char: "🖐️", name_ko: "손 펼치기", name_en: "hand with fingers splayed", tags: ["손", "펼치기", "stop", "hand", "splay", "stop"] },
    { char: "✋", name_ko: "손 들어올리기", name_en: "raised hand", tags: ["손", "들어올리기", "stop", "hand", "raise", "stop"] },
    { char: "🖖", name_ko: "불칸 인사", name_en: "vulcan salute", tags: ["손", "인사", "스타트렉", "hand", "salute", "startrek"] },
    { char: "👌", name_ko: "OK 손가락", name_en: "OK hand", tags: ["손", "OK", "좋아", "hand", "ok", "good"] },
    { char: "🤌", name_ko: "손가락 모으기", name_en: "pinched fingers", tags: ["손", "모으기", "이탈리아", "hand", "pinch", "italy"] },
    { char: "🤏", name_ko: "손가락 집기", name_en: "pinching hand", tags: ["손", "집기", "작음", "hand", "pinch", "small"] },
    { char: "✌️", name_ko: "승리 손가락", name_en: "victory hand", tags: ["손", "승리", "V", "hand", "victory", "v"] },
    { char: "🤞", name_ko: "손가락 교차", name_en: "crossed fingers", tags: ["손", "교차", "행운", "hand", "cross", "luck"] },
    { char: "🤟", name_ko: "사랑 손가락", name_en: "love-you gesture", tags: ["손", "사랑", "I love you", "hand", "love", "ily"] },
    { char: "🤘", name_ko: "악마 뿔", name_en: "sign of the horns", tags: ["손", "악마", "록", "hand", "devil", "rock"] },
    { char: "🤙", name_ko: "전화 손가락", name_en: "call me hand", tags: ["손", "전화", "연락", "hand", "phone", "call"] },
    { char: "👈", name_ko: "왼쪽 가리키기", name_en: "backhand index pointing left", tags: ["손", "왼쪽", "가리키기", "hand", "left", "point"] },
    { char: "👉", name_ko: "오른쪽 가리키기", name_en: "backhand index pointing right", tags: ["손", "오른쪽", "가리키기", "hand", "right", "point"] },
    { char: "👆", name_ko: "위 가리키기", name_en: "backhand index pointing up", tags: ["손", "위", "가리키기", "hand", "up", "point"] },
    { char: "🖕", name_ko: "가운데 손가락", name_en: "middle finger", tags: ["손", "가운데", "욕", "hand", "middle", "rude"] },
    { char: "👇", name_ko: "아래 가리키기", name_en: "backhand index pointing down", tags: ["손", "아래", "가리키기", "hand", "down", "point"] },
    { char: "☝️", name_ko: "위 손가락", name_en: "index pointing up", tags: ["손", "위", "가리키기", "hand", "up", "point"] },
    { char: "👍", name_ko: "엄지 올리기", name_en: "thumbs up", tags: ["손", "엄지", "좋아", "hand", "thumb", "good"] },
    { char: "👎", name_ko: "엄지 내리기", name_en: "thumbs down", tags: ["손", "엄지", "싫어", "hand", "thumb", "bad"] },
    { char: "✊", name_ko: "주먹", name_en: "raised fist", tags: ["손", "주먹", "힘", "hand", "fist", "power"] },
    { char: "👊", name_ko: "주먹 부딪히기", name_en: "oncoming fist", tags: ["손", "주먹", "부딪히기", "hand", "fist", "bump"] },
    { char: "🤛", name_ko: "왼쪽 주먹", name_en: "left-facing fist", tags: ["손", "주먹", "왼쪽", "hand", "fist", "left"] },
    { char: "🤜", name_ko: "오른쪽 주먹", name_en: "right-facing fist", tags: ["손", "주먹", "오른쪽", "hand", "fist", "right"] },
    { char: "👏", name_ko: "박수", name_en: "clapping hands", tags: ["손", "박수", "축하", "hand", "clap", "celebration"] },
    { char: "🙌", name_ko: "손 들기", name_en: "raising hands", tags: ["손", "들기", "축하", "hand", "raise", "celebration"] },
    { char: "👐", name_ko: "손 펼치기", name_en: "open hands", tags: ["손", "펼치기", "열기", "hand", "open", "spread"] },
    { char: "🤲", name_ko: "손 모으기", name_en: "palms up together", tags: ["손", "모으기", "기도", "hand", "together", "pray"] },
    { char: "🤝", name_ko: "악수", name_en: "handshake", tags: ["손", "악수", "인사", "hand", "shake", "greeting"] },
    { char: "🙏", name_ko: "손 모으기", name_en: "folded hands", tags: ["손", "모으기", "기도", "hand", "fold", "pray"] },
    { char: "✍️", name_ko: "글쓰기", name_en: "writing hand", tags: ["손", "글쓰기", "작문", "hand", "write", "writing"] },
    { char: "💅", name_ko: "네일 아트", name_en: "nail polish", tags: ["손", "네일", "미용", "hand", "nail", "beauty"] },
    { char: "🤳", name_ko: "셀카", name_en: "selfie", tags: ["손", "셀카", "사진", "hand", "selfie", "photo"] },
    { char: "💪", name_ko: "근육", name_en: "flexed biceps", tags: ["손", "근육", "힘", "hand", "muscle", "power"] },
    { char: "🦾", name_ko: "기계 팔", name_en: "mechanical arm", tags: ["팔", "기계", "로봇", "arm", "mechanical", "robot"] },
    { char: "🦿", name_ko: "기계 다리", name_en: "mechanical leg", tags: ["다리", "기계", "로봇", "leg", "mechanical", "robot"] },
    { char: "🦵", name_ko: "다리", name_en: "leg", tags: ["다리", "신체", "body", "leg", "body", "body"] },
    { char: "🦶", name_ko: "발", name_en: "foot", tags: ["발", "신체", "body", "foot", "body", "body"] },
    { char: "👂", name_ko: "귀", name_en: "ear", tags: ["귀", "신체", "body", "ear", "body", "body"] },
    { char: "🦻", name_ko: "보청기 귀", name_en: "ear with hearing aid", tags: ["귀", "보청기", "청각", "ear", "hearing aid", "hearing"] },
    { char: "👃", name_ko: "코", name_en: "nose", tags: ["코", "신체", "body", "nose", "body", "body"] },
    { char: "🧠", name_ko: "뇌", name_en: "brain", tags: ["뇌", "신체", "생각", "brain", "body", "thinking"] },
    { char: "🫀", name_ko: "심장", name_en: "anatomical heart", tags: ["심장", "신체", "생명", "heart", "body", "life"] },
    { char: "🫁", name_ko: "폐", name_en: "lungs", tags: ["폐", "신체", "호흡", "lungs", "body", "breath"] },
    { char: "🦷", name_ko: "이빨", name_en: "tooth", tags: ["이빨", "신체", "구강", "tooth", "body", "oral"] },
    { char: "🦴", name_ko: "뼈", name_en: "bone", tags: ["뼈", "신체", "골격", "bone", "body", "skeleton"] },
    { char: "👀", name_ko: "눈", name_en: "eyes", tags: ["눈", "신체", "시각", "eyes", "body", "vision"] },
    { char: "👁️", name_ko: "눈", name_en: "eye", tags: ["눈", "신체", "시각", "eye", "body", "vision"] },
    { char: "👅", name_ko: "혀", name_en: "tongue", tags: ["혀", "신체", "맛", "tongue", "body", "taste"] },
    { char: "👄", name_ko: "입", name_en: "mouth", tags: ["입", "신체", "말", "mouth", "body", "speech"] },
  ],
  hearts: [
    { char: "❤️", name_ko: "빨간 하트", name_en: "red heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🧡", name_ko: "주황 하트", name_en: "orange heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💛", name_ko: "노란 하트", name_en: "yellow heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💚", name_ko: "초록 하트", name_en: "green heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💙", name_ko: "파란 하트", name_en: "blue heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💜", name_ko: "보라 하트", name_en: "purple heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🖤", name_ko: "검은 하트", name_en: "black heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🤍", name_ko: "흰 하트", name_en: "white heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🤎", name_ko: "갈색 하트", name_en: "brown heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💔", name_ko: "깨진 하트", name_en: "broken heart", tags: ["슬픔", "이별", "상실", "sad", "breakup", "loss"] },
    { char: "❣️", name_ko: "하트 느낌표", name_en: "heart exclamation", tags: ["사랑", "강조", "감정", "love", "emphasis", "emotion"] },
    { char: "💕", name_ko: "두 개의 분홍 하트", name_en: "two hearts", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💞", name_ko: "회전하는 하트", name_en: "revolving hearts", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💓", name_ko: "뛰는 하트", name_en: "beating heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💗", name_ko: "커지는 하트", name_en: "growing heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💖", name_ko: "반짝이는 하트", name_en: "sparkling heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💘", name_ko: "화살이 박힌 하트", name_en: "heart with arrow", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💝", name_ko: "리본이 달린 하트", name_en: "heart with ribbon", tags: ["사랑", "하트", "선물", "love", "heart", "gift"] },
    { char: "💟", name_ko: "하트 장식", name_en: "heart decoration", tags: ["사랑", "하트", "장식", "love", "heart", "decoration"] },
    { char: "♥️", name_ko: "하트 수트", name_en: "heart suit", tags: ["하트", "카드", "사랑", "heart", "card", "love"] },
    { char: "❤", name_ko: "빨간 하트", name_en: "red heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🧡", name_ko: "주황 하트", name_en: "orange heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💛", name_ko: "노란 하트", name_en: "yellow heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💚", name_ko: "초록 하트", name_en: "green heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💙", name_ko: "파란 하트", name_en: "blue heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💜", name_ko: "보라 하트", name_en: "purple heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🖤", name_ko: "검은 하트", name_en: "black heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🤍", name_ko: "흰 하트", name_en: "white heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🤎", name_ko: "갈색 하트", name_en: "brown heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💔", name_ko: "깨진 하트", name_en: "broken heart", tags: ["슬픔", "이별", "상실", "sad", "breakup", "loss"] },
    { char: "❣️", name_ko: "하트 느낌표", name_en: "heart exclamation", tags: ["사랑", "강조", "감정", "love", "emphasis", "emotion"] },
    { char: "💕", name_ko: "두 개의 분홍 하트", name_en: "two hearts", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💞", name_ko: "회전하는 하트", name_en: "revolving hearts", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💓", name_ko: "뛰는 하트", name_en: "beating heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💗", name_ko: "커지는 하트", name_en: "growing heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💖", name_ko: "반짝이는 하트", name_en: "sparkling heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💘", name_ko: "화살이 박힌 하트", name_en: "heart with arrow", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💝", name_ko: "리본이 달린 하트", name_en: "heart with ribbon", tags: ["사랑", "하트", "선물", "love", "heart", "gift"] },
    { char: "💟", name_ko: "하트 장식", name_en: "heart decoration", tags: ["사랑", "하트", "장식", "love", "heart", "decoration"] },
    { char: "♥️", name_ko: "하트 수트", name_en: "heart suit", tags: ["하트", "카드", "사랑", "heart", "card", "love"] },
    { char: "❤", name_ko: "빨간 하트", name_en: "red heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🧡", name_ko: "주황 하트", name_en: "orange heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💛", name_ko: "노란 하트", name_en: "yellow heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💚", name_ko: "초록 하트", name_en: "green heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💙", name_ko: "파란 하트", name_en: "blue heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💜", name_ko: "보라 하트", name_en: "purple heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🖤", name_ko: "검은 하트", name_en: "black heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🤍", name_ko: "흰 하트", name_en: "white heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "🤎", name_ko: "갈색 하트", name_en: "brown heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💔", name_ko: "깨진 하트", name_en: "broken heart", tags: ["슬픔", "이별", "상실", "sad", "breakup", "loss"] },
    { char: "❣️", name_ko: "하트 느낌표", name_en: "heart exclamation", tags: ["사랑", "강조", "감정", "love", "emphasis", "emotion"] },
    { char: "💕", name_ko: "두 개의 분홍 하트", name_en: "two hearts", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💞", name_ko: "회전하는 하트", name_en: "revolving hearts", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💓", name_ko: "뛰는 하트", name_en: "beating heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💗", name_ko: "커지는 하트", name_en: "growing heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💖", name_ko: "반짝이는 하트", name_en: "sparkling heart", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💘", name_ko: "화살이 박힌 하트", name_en: "heart with arrow", tags: ["사랑", "하트", "감정", "love", "heart", "emotion"] },
    { char: "💝", name_ko: "리본이 달린 하트", name_en: "heart with ribbon", tags: ["사랑", "하트", "선물", "love", "heart", "gift"] },
    { char: "💟", name_ko: "하트 장식", name_en: "heart decoration", tags: ["사랑", "하트", "장식", "love", "heart", "decoration"] },
    { char: "♥️", name_ko: "하트 수트", name_en: "heart suit", tags: ["하트", "카드", "사랑", "heart", "card", "love"] },
  ],
  // ... 나머지 카테고리도 계속 추가해야 하지만 파일이 너무 커질 수 있으므로
  // 스크립트로 실행하여 JSON 파일을 생성하는 방식이 좋습니다.
};

// 중복 제거 및 JSON 생성
function generateEmojiJSON() {
  const allEmojis = [];
  const seenChars = new Set();
  const seenNameChar = new Set();

  // 각 카테고리에서 이모지 추출
  for (const [category, items] of Object.entries(emojiData)) {
    for (const item of items) {
      // char 중복 체크
      if (seenChars.has(item.char)) {
        console.warn(`중복 char 발견: ${item.char} (${item.name_ko})`);
        continue;
      }
      seenChars.add(item.char);

      // name_ko + char 조합 중복 체크
      const key = `${item.name_ko}|${item.char}`;
      if (seenNameChar.has(key)) {
        console.warn(`중복 name_ko+char 발견: ${item.name_ko} + ${item.char}`);
        continue;
      }
      seenNameChar.add(key);

      allEmojis.push({
        char: item.char,
        category: category,
        name_ko: item.name_ko,
        name_en: item.name_en,
        tags: item.tags,
      });
    }
  }

  // JSON 파일로 저장
  const outputPath = path.join(__dirname, "../data/emojis_ko.json");
  fs.writeFileSync(outputPath, JSON.stringify(allEmojis, null, 2), "utf-8");
  console.log(`✅ 총 ${allEmojis.length}개의 이모지 데이터가 생성되었습니다.`);
  console.log(`📁 저장 위치: ${outputPath}`);
}

generateEmojiJSON();


